apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: eksa-clusters-config
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: clusters-config
  url: https://github.com/tanthanhkid/eksa-flux-system.git
